// Acquire data from Project Werk Survey form (Project WERK)

version 14
clear
set more off

redcap_use 	record_id ///
			age ///
			dob ///
			hispanic ///
			race ///
			race_othspec ///
			relstat ///
			hischool ///
			higrade ///
			hsdegree ///
			zipcode ///
			intersection_ew ///
			intersection_ns ///
			empstatus ///
			disability ///
			emploss ///
			missedmeals ///
			moneyprob ///
			reschange ///
			healthins ///
			healthinstype ///
			spendnights ///
			spendnights_othspec ///
			gender_birth ///
			genderid ///
			genderid_othspec ///
			sexorient ///
			sexorient_othspec ///
			sexcont_women ///
			sexcont_men ///
			sexcont_transmen ///

			soc_name1 ///
			soc_name2 ///
			soc_name3 ///
			soc_name4 ///
			soc_name5 ///
			soc_name6 ///
			soc_name7 ///
			soc_name8 ///
			soc_name9 ///
			soc_name10 ///
			soc_network ///
			soc_rship1 ///
			soc_age1 ///
			soc_race1 ///
			soc_gender1 ///
			soc_hied1 ///
			soc_live1 ///
			soc_rship2 ///
			soc_age2 ///
			soc_race2 ///
			soc_gender2 ///
			soc_hied2 ///
			soc_live2 ///
			soc_rship3 ///
			soc_age3 ///
			soc_race3 ///
			soc_gender3 ///
			soc_hied3 ///
			soc_live3 ///
			soc_rship4 ///
			soc_age4 ///
			soc_race4 ///
			soc_gender4 ///
			soc_hied4 ///
			soc_live4 ///
			soc_rship5 ///
			soc_age5 ///
			soc_race5 ///
			soc_gender5 ///
			soc_hied5 ///
			soc_live5 ///
			soc_cell1 ///
			soc_cell2 ///
			soc_cell3 ///
			soc_cell4 ///
			soc_cell5 ///
			soc_cellchange1 ///
			soc_cellchange2 ///
			soc_cellchange3 ///
			soc_cellchange4 ///
			soc_cellchange5 ///
			soc_move1 ///
			soc_move2 ///
			soc_move3 ///
			soc_move4 ///
			soc_move5 ///
			soc_comm1 ///
			soc_comm2 ///
			soc_comm3 ///
			soc_comm4 ///
			soc_comm5 ///
			soc_visit1 ///
			soc_visit2 ///
			soc_visit3 ///
			soc_visit4 ///
			soc_visit5 ///
			soc_avail1 ///
			soc_avail2 ///
			soc_avail3 ///
			soc_avail4 ///
			soc_avail5 ///
			soc_betray1 ///
			soc_betray2 ///
			soc_betray3 ///
			soc_betray4 ///
			soc_betray5 ///
			soc_knowmsm1 ///
			soc_knowmsm2 ///
			soc_knowmsm3 ///
			soc_knowmsm4 ///
			soc_knowmsm5 ///
			soc_sexpref1 ///
			soc_sexpref2 ///
			soc_sexpref3 ///
			soc_sexpref4 ///
			soc_sexpref5 ///
			soc_substance1 ///
			soc_substance2 ///
			soc_substance3 ///
			soc_substance4 ///
			soc_substance5 ///
			soc_jail1 ///
			soc_jail2 ///
			soc_jail3 ///
			soc_jail4 ///
			soc_jail5 ///

			resil_adapt ///
			resil_deal ///
			resil_funny ///
			resil_cope ///
			resil_bounce ///
			resil_overcome ///
			resil_focus ///
			resil_discourage ///
			resil_strong ///
			resil_handle ///

			closefriends ///
			closerelatives ///
			supp_confined ///
			supp_listen ///
      supp_crisis ///
      supp_doctor ///
      supp_love ///
      supp_fun ///
      supp_info ///
      supp_confide ///
      supp_hug ///
      supp_relax ///
      supp_cook ///
      supp_advice ///
      supp_mindoff ///
      supp_chores ///
      supp_private ///
      supp_problem ///
      supp_enjoy ///
      supp_understand ///
      supp_wanted ///
      houseball ///
      closehouse ///
      family ///

      depress_bother ///
      depress_focus ///
      depress_depressed ///
      depress_effort ///
      depress_hope ///
      depress_fear ///
      depress_sleep ///
      depress_happy ///
      depress_lonely ///
      depress_getgoing ///

      anx_nervous ///
      anx_control ///
      anx_worry ///
      anx_relax ///
      anx_restless ///
      anx_annoyed ///
      anx_afraid ///

      rally ///
      rallyissues ///
      policestop ///
      policestop_num ///
      policearrest ///
      policearrest_num ///
      policestation ///
      policestation_num ///
      policejail ///
      policejail_num ///
      stop_legit ///
      stop_askname ///
      stop_frisk ///
      stop_search ///
      stop_bully ///
      stop_respect ///
      stop_curse ///
      stop_threat ///
      stop_force ///
      stop_cuff ///
      stop_weapon ///
      stop_arrest ///
      stop_satisfied ///
      stop_safe ///
      stop_scared ///
      stop_angry ///

			assist_tobacco ///
			assist_tobacco3m ///
			assist_inhalants ///
			assist_inhalants3m ///
			assist_halluc ///
			assist_halluc3m ///
			assist_alcohol ///
			assist_alcohol3m ///
			assist_alc_desire ///
			assist_alc_prob ///
			assist_alc_expect ///
			assist_alc_concern ///
			assist_alc_control ///
			assist_cannabis ///
			assist_cannabis3m ///
			assist_cann_desire ///
			assist_cann_prob ///
			assist_cann_expect ///
			assist_cann_concern ///
			asssist_cann_control ///
			assist_coke ///
			assist_coke3m ///
			assist_coke_desire ///
			assist_coke_prob ///
			assist_coke_expect ///
			assist_coke_concern ///
			assist_coke_control ///
			assist_stim ///
			assist_stim3m ///
			assist_stim_desire ///
			assist_stim_prob ///
			assist_stim_expect ///
			assist_stim_concern ///
			assist_stim_conrtol ///
			assist_sedatives ///
			assist_sed3m ///
			assist_sed_desire ///
			assist_sed_prob ///
			assist_sed_expect ///
			assist_sed_concern ///
			assist_sed_control ///
			assist_opioids ///
			assist_opioids3m ///
			assist_opioids_desire ///
			assist_opioids_prob ///
			assist_opioids_expect ///
			assist_opioids_concern ///
			assist_opioids_control ///
			assist_other ///
			assist_other3m ///
			assist_other_desire ///
			assist_other_prob ///
			assist_other_expect ///
			assist_other_concern ///
			assist_other_control ///
			assist_inject ///

			arba_anal3m ///
			arba_anal_partners ///
			arba_anal_hivpos ///
			arba_anal_hivneg ///
			arba_anal_hivunknown ///
			arba_anal_exchange ///
			arba_recept_times ///
			arba_recept_intox ///
			arba_recept_nocond ///
			arba_recept_intoxnocond ///
			arba_insert_times ///
			arba_insert_intox ///
			arba_insert_nocondom ///
			arba_insert_intoxnocondom ///
			arba_vag3m ///
			arba_vag_partners ///
			arba_vag_hivpos ///
			arba_vag_hivneg ///
			arba_vag_hivunknown ///
			arba_vag_exchange ///
			arba_insvag_times ///
			arba_insvag_intox ///
			arba_insvag_nocondom ///
			arba_insvag_intoxnocondom ///
			arba_last ///
			arba_laststatus ///
			arba_laststatushow ///
			arba_laststatushow_oth ///
			arba_lastrace ///
			arba_lastraceoth ///
			arba_lastrel ///
			arba_lastlong ///
			arba_lastage ///
			arba_lastdrink ///
			arba_lastdrugs ///
			arba_lastgender ///
			arba_last_insanal ///
			arba_last_insanalcond ///
			arba_last_recanal ///
			arba_last_recanalcond ///
			arba_last_insvag ///
			arba_last_insvagcond ///

			sti_chlamydia ///
			sti_gonorrhea ///
			sti_syph ///
			sti_other ///
			sti_otherspec ///
			sti_transition ///
			sti_hivlikely ///
			sti_prep_aware ///
			sti_prep_on ///
			sti_prep_network ///
			sti_pep_aware ///
			sti_pep_taken ///
			sti_pep_network ///
			sti_prep_source ///
			sti_prep_sourceoth ///
			sti_prep_should ///
			sti_prep_condoms ///
			sti_prep_sleep ///
			sti_prep_irrespons ///
			sti_prep_risky ///
			sti_prep_smart ///
			sti_prep_notrust ///
			sti_prep_sexdrive ///
			sti_prep_lie ///
			sti_prep_respons ///
			sti_prep_nocondom ///
			sti_prep_anyone ///
			sti_prep_cdc ///
			sti_prep_pharma ///
			sti_prep_longterm ///
			sti_prep_sideeff ///
			sti_prep_medseff ///
			sti_prep_protect ///
			sti_prep_daily ///
			sti_prep_morerisk ///
			sti_prep_atrisk ///
			sti_prep_partner ///
			sti_prep_seepill ///
			sti_prep_seehiv ///
			sti_prep_md ///
			sti_prep_talkmd ///
			sti_prep_othersti ///
			sti_prep_pay ///
			sti_prep_testing ///
			sti_prep_care ///
			sti_prep_counsel ///
			sti_prep_text ///
			sti_prep_sexcounsel ///
			sti_prep_primarymd ///
			sti_prep_group ///
			sti_prep_mental ///
			sti_prep_job ///
			sti_prep_housing ///
			sti_healthcare_afford ///
			sti_healthcare_primary///
			sti_healthcare_race ///
			sti_healthcare_sexorient///

			viol_event ///
			viol_fear ///
			viol_reexp ///
			viol_avoidtalk ///
			viol_avoid ///
			viol_recall ///
			viol_hobby ///
			viol_detach ///
			viol_numb ///
			viol_die ///
			gateway_3 ///
			viol_sleep ///
			viol_anger ///
			viol_focus ///
			viol_nerve ///
			viol_startle ///
			gateway_2 ///
			viol_interfere ///
			viol_closedeath ///
			viol_closeinjure ///
			viol_closeattack ///
			viol_sawbeat ///
			viol_victim ///
			viol_sawbody ///
			viol_sawgun ///

			debrf_feeling ///
			debrf_upset ///
			debrf_harm ///
			debrf_thoughthurt ///
			debrf_planhurt ///
			debrf_plandetails ///
			debrf_haveweapon ///
			debrf_prevhurt ///
			debrf_hospuic ///
			debrf_anyoneknow ///
			debrf_therapist ///

			project_werk_survey_complete ///
			using tmp/cd/redcap, events("prepr_survey_arm_1")

// Rename vars

// Recode categorical variables

// Reformat dates
